// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniOidcIdp.Persistence.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerIdpDbContext))]
    [Migration("20260920183301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorizationCodeRow", b =>
                {
                    b.Property<byte[]>("CodeHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeHash");

                    b.HasIndex("ExpiresAtUnix");

                    b.ToTable("AuthorizationCodes");
                });

            modelBuilder.Entity("ClientRow", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostLogoutRedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("RefreshTokenRow", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("bigint");

                    b.Property<long>("FamilyCreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("IssuedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAtUnix");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Subject");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RoleMappingRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("GroupName", "Role")
                        .IsUnique();

                    b.ToTable("RoleMappings");
                });

            modelBuilder.Entity("SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SigningKeyRow", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Kid");

                    b.ToTable("SigningKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
