// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiniOidcIdp.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteIdpDbContext))]
    partial class SqliteIdpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AuthorizationCodeRow", b =>
                {
                    b.Property<byte[]>("CodeHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CodeHash");

                    b.HasIndex("ExpiresAtUnix");

                    b.ToTable("AuthorizationCodes");
                });

            modelBuilder.Entity("ClientRow", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostLogoutRedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("RefreshTokenRow", b =>
                {
                    b.Property<byte[]>("TokenHash")
                        .HasMaxLength(32)
                        .HasColumnType("BLOB");

                    b.Property<long>("ExpiresAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FamilyCreatedAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("IssuedAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAtUnix");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Subject");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RoleMappingRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupName", "Role")
                        .IsUnique();

                    b.ToTable("RoleMappings");
                });

            modelBuilder.Entity("SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("SigningKeyRow", b =>
                {
                    b.Property<string>("Kid")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUnix")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EncryptedPrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Kid");

                    b.ToTable("SigningKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
